### ISSUE TITLE
Import into Objective - C Project?

### ISSUE THREAD

**Issue by azeemOshaan** [lucabecchetti/swiftmultiselect#1]
Is there a way to get this working with an Obj-C project? I am able to successfully @import 'SwiftMultiSelect' in my Obj-C view controller but unable to add the delegate 'SwiftMultiSelectDelegate'. Am I missing anything?

Please help me out. Thanks

**Comment by lucabecchetti** [comment]
Hi, i have never tested it with objective-c, what is the error?
