### ISSUE TITLE
OnItsWay using SwiftMultiSelect

### ISSUE THREAD

**Issue by juanwall** [lucabecchetti/swiftmultiselect#2]
Great repo!

We're using SwiftMultiSelect in OnItsWay: https://itunes.apple.com/us/app/onitsway-deliveries-made-easy/id1190157855?ls=1&mt=8

I saw in your readme where you wanted to add a list of projects that are using the repo.

**Comment by lucabecchetti** [comment]
Added to our list! thanks!
