### ISSUE TITLE
Selected user images are shifted down

### ISSUE THREAD

**Issue by yarodevuci** [lucabecchetti/swiftmultiselect#4]
Hi
How can I fix this?
I want them centered in the row
![5cc5b975-2ed5-4273-a87b-b9ce7e2756bb](https://user-images.githubusercontent.com/13408859/34599126-a6dec84a-f1a5-11e7-97a7-928223126d47.jpeg)

**Comment by lucabecchetti** [comment]
It seems that mask to bound is not enabled

**Comment by yarodevuci** [comment]
@lucabecchetti Where do I check for that?
 
in "open fileprivate(set) lazy var imageAvatar: UIImageView" it's set to true

**Comment by yarodevuci** [comment]
Fixed! I adjusted image size..

**Comment by lucabecchetti** [comment]
Thanks! Share your app if you want!!!

**Comment by yarodevuci** [comment]
@lucabecchetti  Of course. Please add it to your list of apps
Name is Eclipse Chat, I will release an update very soon
